remote_theme: bagustris/primer2-theme
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

title: primer2
url: "https://bagustris.github.io"
baseurl: "/primer2"
repository: bagustris/primer2
description: Documentation for primer2-theme — a two-column Jekyll theme for GitHub Pages

exclude:
  - README.md
  - Gemfile
  - vendor/
